const items = [
    {
        id: "1password",
        name: "1Password",
        img: "/list/1password.png",
        browser: "/list/all.png",
        url: "https://1password.com/pt/downloads/browser-extension/",
        corporation: "AgileBits Inc.",
    },
    {
        id: "adblock",
        name: "Adblock",
        img: "/list/adblock.png",
        browser: "/list/all.png",
        url: "https://adblockplus.org/en/download",
        corporation: "Eyeo GmbH",
    },
    {
        id: "bitwarden",
        name: "Bitwarden",
        img: "/list/bitwarden.png",
        browser: "/list/all.png",
        url: "https://bitwarden.com/download/",
        corporation: "Bitwarden",
    },
    {
        id: "bonjourr",
        name: "Bonjourr",
        img: "/list/bonjourr.png",
        browser: "/list/all.png",
        url: "https://bonjourr.fr/use-bonjourr",
        corporation: "Victor & Tahoe",
    },
    {
        id: "darkreader",
        name: "Dark Reader",
        img: "/list/darkreader.png",
        browser: "/list/all.png",
        url: "https://darkreader.org/",
        corporation: "Dark Reader",
    },
    {
        id: "gamersclub",
        name: "GamersClub Booster",
        browser: "/list/chrome.png",
        img: "/list/gamersclub.png",
        url: "https://chrome.google.com/webstore/detail/gamersclub-booster/dahnmmlhchpmmlgebpkpaofbefjdlpin",
        corporation: "Gamers Club",
    },
    {
        id: "gamersclub",
        name: "GamersClub Booster",
        browser: "/list/firefox.png",
        img: "/list/gamersclub.png",
        url: "https://addons.mozilla.org/pt-BR/firefox/addon/gamersclub-booster/",
        corporation: "Gamers Club",
    },
    {
        id: "gumboc",
        name: "Gumbo: Twitch",
        browser: "/list/chrome.png",
        img: "/list/gumbo.png",
        url: "https://chrome.google.com/webstore/detail/gumbo-twitch-companion/aalmjfpohaedoddkobnibokclgeefamn",
        corporation: "Seldszar",
    },
    {
        id: "gumbof",
        name: "Gumbo: Twitch",
        browser: "/list/firefox.png",
        img: "/list/gumbo.png",
        url: "https://addons.mozilla.org/en-US/firefox/addon/gumbo-twitch-companion/",
        corporation: "Seldszar",
    },
    {
        id: "soundbooster",
        name: "Sound Booster",
        img: "/list/soundbooster.png",
        browser: "/list/chrome.png",
        url: "https://chrome.google.com/webstore/detail/sound-booster-increase-yo/njcpapmgiimlmlelomamnobmdmhpbfhd",
        corporation: "ExtBooster",
    },
    {
        id: "tabmuter",
        name: "Tab Muter",
        img: "/list/tabmuter.png",
        browser: "/list/chrome.png",
        url: "https://chrome.google.com/webstore/detail/tab-muter/bnclejfcblondkjliiblkojdeloomadd",
        corporation: "tab.muter.computer",
    },
];

export default items;
